name: CD for Go Code
on:
  create:
    tags:
      - v*
      
jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.2
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18
      
      - name: Install dependencies
        run: |
          go mod init calc # for go mod. If we use go build, it will do the same for the 3 lines.
          go mod tidy      
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
